import type { MockClientServicePlan } from './types';

export const mockServicePlans: MockClientServicePlan[] = [
  {
    id: 'plan-limmat-weekly',
    clientId: 'client-limmat',
    frequencyType: 'WEEKLY',
    weekdays: ['MONDAY'],
    recurrenceStartDate: '2026-06-01',
    startTime: '09:00',
    defaultHours: 3,
    defaultPeopleCount: 2,
    clientHourlyRate: 48,
    vatRate: 8.1,
    operationalNotes: 'Entrada por la puerta lateral.',
    active: true,
  },
  {
    id: 'plan-helvetia-biweekly',
    clientId: 'client-helvetia',
    frequencyType: 'BIWEEKLY',
    weekdays: ['MONDAY'],
    recurrenceStartDate: '2026-06-15',
    startTime: '13:30',
    defaultHours: 3,
    defaultPeopleCount: 1,
    clientHourlyRate: 52,
    vatRate: 8.1,
    billingNotes: 'Facturar por quincena.',
    active: true,
  },
  {
    id: 'plan-atelier-multi',
    clientId: 'client-atelier',
    frequencyType: 'MULTIPLE_DAYS_PER_WEEK',
    weekdays: ['MONDAY', 'THURSDAY'],
    recurrenceStartDate: '2026-06-02',
    startTime: '18:00',
    defaultHours: 1.5,
    defaultPeopleCount: 1,
    clientHourlyRate: 50,
    vatRate: 8.1,
    active: true,
  },
  {
    id: 'plan-rivera-paused',
    clientId: 'client-rivera',
    frequencyType: 'WEEKLY',
    weekdays: ['FRIDAY'],
    recurrenceStartDate: '2026-06-06',
    startTime: '16:00',
    defaultHours: 2,
    defaultPeopleCount: 1,
    clientHourlyRate: 45,
    vatRate: 8.1,
    active: false,
  },
];
