import type { MockClient } from './types';

export const mockClients: MockClient[] = [
  {
    id: 'client-limmat',
    displayName: 'Praxis Limmatblick',
    contactType: 'Empresa',
    email: 'kontakt@limmatblick.test',
    phone: '+41 44 555 10 20',
    address: 'Limmatstrasse 12',
    city: 'Zürich',
    country: 'CH',
    language: 'DE',
    status: 'ACTIVE',
  },
  {
    id: 'client-helvetia',
    displayName: 'Helvetia Treuhand AG',
    contactType: 'Empresa',
    email: 'office@helvetia-treuhand.test',
    city: 'Zürich',
    country: 'CH',
    language: 'DE',
    status: 'ACTIVE',
  },
  {
    id: 'client-atelier',
    displayName: 'Atelier Nord',
    contactType: 'Empresa',
    phone: '+41 44 555 18 80',
    city: 'Winterthur',
    country: 'CH',
    language: 'DE',
    status: 'ACTIVE',
  },
  {
    id: 'client-rivera',
    displayName: 'Familia Rivera',
    contactType: 'Privado',
    city: 'Uster',
    country: 'CH',
    language: 'ES',
    status: 'PAUSED',
  },
];
