import type { MockPendingBillingVisit } from './types';

export const mockPendingBillingVisits: MockPendingBillingVisit[] = [
  {
    id: 'billing-limmat-1',
    clientId: 'client-limmat',
    clientName: 'Praxis Limmatblick',
    serviceDate: '2026-06-03',
    description: 'Limpieza semanal consultorios',
    employeeNames: ['Ana Medina', 'Luis Keller'],
    peopleCount: 2,
    billableHours: 6,
    clientHourlyRate: 48,
    vatRate: 8.1,
    visitStatus: 'COMPLETED',
    invoiceStatus: 'NOT_INVOICED',
  },
  {
    id: 'billing-limmat-2',
    clientId: 'client-limmat',
    clientName: 'Praxis Limmatblick',
    serviceDate: '2026-06-10',
    description: 'Limpieza semanal consultorios',
    employeeNames: ['Mara Novak'],
    peopleCount: 1,
    billableHours: 3,
    clientHourlyRate: 48,
    vatRate: 8.1,
    visitStatus: 'COMPLETED',
    invoiceStatus: 'READY_TO_INVOICE',
  },
  {
    id: 'billing-helvetia-1',
    clientId: 'client-helvetia',
    clientName: 'Helvetia Treuhand AG',
    serviceDate: '2026-06-05',
    description: 'Limpieza oficinas',
    employeeNames: ['Ana Medina', 'Mara Novak'],
    peopleCount: 2,
    billableHours: 5.5,
    clientHourlyRate: 52,
    vatRate: 8.1,
    visitStatus: 'COMPLETED',
    invoiceStatus: 'NOT_INVOICED',
  },
  {
    id: 'billing-rivera-cancelled',
    clientId: 'client-rivera',
    clientName: 'Familia Rivera',
    serviceDate: '2026-06-06',
    description: 'Visita cancelada',
    employeeNames: [],
    peopleCount: 0,
    billableHours: 0,
    clientHourlyRate: 45,
    vatRate: 8.1,
    visitStatus: 'CANCELLED',
    invoiceStatus: 'NOT_INVOICED',
  },
  {
    id: 'billing-atelier-invoiced',
    clientId: 'client-atelier',
    clientName: 'Atelier Nord',
    serviceDate: '2026-06-07',
    description: 'Servicio ya facturado',
    employeeNames: ['Luis Keller'],
    peopleCount: 1,
    billableHours: 2,
    clientHourlyRate: 50,
    vatRate: 8.1,
    visitStatus: 'COMPLETED',
    invoiceStatus: 'INVOICED',
  },
];
