import type { MockPayrollHourRecord } from './types';

export const mockPayrollHourRecords: MockPayrollHourRecord[] = [
  {
    id: 'payroll-ana-limmat-1',
    employeeId: 'employee-ana',
    employeeName: 'Ana Medina',
    employeeInitials: 'AM',
    serviceDate: '2026-06-03',
    clientName: 'Praxis Limmatblick',
    hoursWorked: 3,
    payRateSnapshot: 28,
    payrollStatus: 'OPEN',
  },
  {
    id: 'payroll-ana-helvetia-1',
    employeeId: 'employee-ana',
    employeeName: 'Ana Medina',
    employeeInitials: 'AM',
    serviceDate: '2026-06-05',
    clientName: 'Helvetia Treuhand AG',
    hoursWorked: 2.5,
    payRateSnapshot: 28,
    payrollStatus: 'APPROVED',
  },
  {
    id: 'payroll-luis-limmat-1',
    employeeId: 'employee-luis',
    employeeName: 'Luis Keller',
    employeeInitials: 'LK',
    serviceDate: '2026-06-03',
    clientName: 'Praxis Limmatblick',
    hoursWorked: 3,
    payRateSnapshot: 30,
    payrollStatus: 'OPEN',
  },
  {
    id: 'payroll-mara-helvetia-1',
    employeeId: 'employee-mara',
    employeeName: 'Mara Novak',
    employeeInitials: 'MN',
    serviceDate: '2026-06-05',
    clientName: 'Helvetia Treuhand AG',
    hoursWorked: 3,
    payRateSnapshot: 27.5,
    payrollStatus: 'OPEN',
  },
  {
    id: 'payroll-zero-hours',
    employeeId: 'employee-luis',
    employeeName: 'Luis Keller',
    employeeInitials: 'LK',
    serviceDate: '2026-06-06',
    clientName: 'Familia Rivera',
    hoursWorked: 0,
    payRateSnapshot: 30,
    payrollStatus: 'OPEN',
  },
  {
    id: 'payroll-locked',
    employeeId: 'employee-mara',
    employeeName: 'Mara Novak',
    employeeInitials: 'MN',
    serviceDate: '2026-06-01',
    clientName: 'Atelier Nord',
    hoursWorked: 2,
    payRateSnapshot: 27.5,
    payrollStatus: 'LOCKED',
  },
];
