import { Prisma } from '@prisma/client';
import { describe, expect, it } from 'vitest';

import { mapServiceVisitRecord } from '../../services/visits/mappers';

describe('visit service mappers', () => {
  it('maps a Prisma ServiceVisit with relations to the Today UI shape', () => {
    const mappedVisit = mapServiceVisitRecord({
      id: 'visit-1',
      clientId: 'client-1',
      servicePlanId: 'plan-1',
      scheduledDate: new Date('2026-06-26T00:00:00.000Z'),
      startedAt: null,
      finishedAt: null,
      status: 'COMPLETED',
      clientHourlyRateSnapshot: new Prisma.Decimal('58.25'),
      vatRateSnapshot: new Prisma.Decimal('8.1'),
      billableHours: new Prisma.Decimal('6'),
      subtotalAmount: new Prisma.Decimal('349.5'),
      vatAmount: new Prisma.Decimal('28.31'),
      totalAmount: new Prisma.Decimal('377.81'),
      invoiceStatus: 'READY_TO_INVOICE',
      bexioInvoiceId: null,
      notes: 'Use side entrance',
      createdById: null,
      createdAt: new Date('2026-06-26T10:00:00.000Z'),
      updatedAt: new Date('2026-06-26T10:00:00.000Z'),
      client: {
        id: 'client-1',
        bexioContactId: null,
        displayName: 'Crystal Travel AG',
        contactType: null,
        companyName: null,
        firstName: null,
        lastName: null,
        email: null,
        phone: null,
        mobile: null,
        address: null,
        street: null,
        houseNo: null,
        postcode: null,
        city: null,
        country: null,
        language: null,
        correspondenceType: null,
        category: null,
        remarks: null,
        status: 'ACTIVE',
        createdAt: new Date('2026-06-01T00:00:00.000Z'),
        updatedAt: new Date('2026-06-01T00:00:00.000Z'),
      },
      servicePlan: {
        id: 'plan-1',
        clientId: 'client-1',
        frequencyType: 'BIWEEKLY',
        weekdays: ['TUESDAY'],
        recurrenceStartDate: new Date('2026-06-02T00:00:00.000Z'),
        startTime: '18:30',
        defaultHours: new Prisma.Decimal('4'),
        defaultPeopleCount: 2,
        clientHourlyRate: new Prisma.Decimal('58.25'),
        vatRate: new Prisma.Decimal('8.1'),
        billingNotes: null,
        operationalNotes: null,
        active: true,
        createdAt: new Date('2026-06-01T00:00:00.000Z'),
        updatedAt: new Date('2026-06-01T00:00:00.000Z'),
      },
      employeeHours: [
        {
          id: 'hour-1',
          visitId: 'visit-1',
          employeeId: 'employee-1',
          hoursWorked: new Prisma.Decimal('3'),
          payRateSnapshot: new Prisma.Decimal('28'),
          payrollStatus: 'OPEN',
          createdAt: new Date('2026-06-26T10:00:00.000Z'),
          updatedAt: new Date('2026-06-26T10:00:00.000Z'),
          employee: {
            id: 'employee-1',
            name: 'Ana Medina',
            initials: 'AM',
            email: null,
            phone: null,
            hourlyPayRate: new Prisma.Decimal('28'),
            status: 'ACTIVE',
            createdAt: new Date('2026-06-01T00:00:00.000Z'),
            updatedAt: new Date('2026-06-01T00:00:00.000Z'),
          },
        },
      ],
    });

    expect(mappedVisit).toEqual({
      id: 'visit-1',
      clientName: 'Crystal Travel AG',
      scheduledDate: '2026-06-26',
      estimatedTime: '18:30',
      frequency: 'BIWEEKLY',
      defaultHours: 4,
      defaultPeopleCount: 2,
      clientHourlyRate: 58.25,
      vatRate: 8.1,
      status: 'COMPLETED',
      notes: 'Use side entrance',
    });
  });
});
